apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new-test-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-test-springboot
    app.kubernetes.io/part-of: new-test-springboot
  name: new-test-springbootc6ba
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: new-test-springboot
    weight: null
status: {}
